version: '3.8'

services:
  db:
    image: postgres:15.4
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      foodapi:

  api:
    build:
      context: ./backend
    image: food_chain_api
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./backend:/app:delegated
    depends_on:
      - db
    command: sh -c ./entrypoint.sh
    networks:
      default:
      foodapi:
    restart: on-failure


volumes:
  db-data:

networks:
  foodapi:
    driver: bridge