"""unique player constraint

Revision ID: 957f42caac82
Revises: c8b92d810b0c
Create Date: 2023-09-26 11:40:13.803610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957f42caac82'
down_revision = 'c8b92d810b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_player', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_constraint('unique_player', type_='unique')

    # ### end Alembic commands ###
