"""create player, game, and round table

Revision ID: 62c99c72add1
Revises:
Create Date: 2023-08-28 14:10:11.633555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c99c72add1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bank_start', sa.Integer(), nullable=False),
                    sa.Column('bank_reserve', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('players',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('hashed_password', sa.String(length=255),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('GamePlayer',
                    sa.Column('game_id', sa.Integer(), nullable=False),
                    sa.Column('player_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
                    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
                    sa.PrimaryKeyConstraint('game_id', 'player_id')
                    )

    op.create_table('rounds',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('round', sa.Integer(), nullable=False),
                    sa.Column('player_id', sa.Integer(), nullable=True),
                    sa.Column('first_burger', sa.Boolean(), nullable=True),
                    sa.Column('first_pizza', sa.Boolean(), nullable=True),
                    sa.Column('first_drink', sa.Boolean(), nullable=True),
                    sa.Column('first_waitress', sa.Boolean(), nullable=True),
                    sa.Column('cfo', sa.Boolean(), nullable=True),
                    sa.Column('unit_price', sa.Integer(), nullable=False),
                    sa.Column('waitresses', sa.Integer(), nullable=False),
                    sa.Column('salaries_paid', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_table('GamePlayer')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
